#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Oct 18, 2019 08:34:47 AM CDT  platform: Darwin

import sys
import lib.UI.EKSManagement as EKSManagement

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def launch_eks(cb_config):
    #print('MainScreen_support.launch_eks')
    #sys.stdout.flush()
    destroy_window()
    EKSManagement.vp_start_gui(cb_config)

def quit():
    #print('MainScreen_support.quit')
    #sys.stdout.flush()
    destroy_window()

def todo():
    print('MainScreen_support.todo')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import lib.UI.MainScreen as MainScreen
    MainScreen.vp_start_gui()




