apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdkdemo
spec:
  selector:
    matchLabels:
      app: sdkdemo
  template:
    metadata:
      labels:
        app: sdkdemo
    spec:
      containers:
      - name: sdkdemo
        image: cbck/cb-sdk-demo:latest
        imagePullPolicy: Always
